version: '3.8'
services:
  traefik:
    image: traefik:v3.0
    command: ["--providers.docker=true", "--entrypoints.web.address=:80"]
    ports: ["80:80"]
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: orion
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]
  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    environment:
      - NEXTAUTH_SECRET=devsecret
      - NEXTAUTH_URL=http://localhost
      - DATABASE_URL=postgresql://orion:orion@postgres:5432/orion
      - NEXT_PUBLIC_LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
    depends_on: [postgres]
  n8n:
    image: n8nio/n8n:latest
    environment:
      - TZ=America/Los_Angeles
      - N8N_SECURE_COOKIE=false
    ports: ["5678:5678"]
  vllm:
    image: vllm/vllm-openai:latest
    command: ["--model", "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"]
    ports: ["8000:8000"]
  mcp:
    image: ghcr.io/your-org/orion-mcp:latest
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LOCAL_LLM_BASE_URL=${LOCAL_LLM_BASE_URL}
    depends_on: [postgres, redis]
volumes:
  pg_data: {}
