required:
  - 01_stack.md
  - 02_scope_faq.csv
  - 03_flow_spec.json
  - 04_prompts.md
  - 05_sheets_setup.md
  - 06_zaps_make.yaml
  - 09_qa_checklist.md
  - 10_kpi_rollup.md
  - 11_sales_playbook.md
  - 12_monitoring.md
  - 13_pull_site_strategy.md
